tasks:
  - init: yarn install && yarn run build
    command: yarn run start
#tasks:
#  - init: npm install
#    command: npm start
ports:
  - port: 3000
    onOpen: open-preview
    
image: gitpod/workspace-full
